image: node:18

pipelines:
  branches:
    master:
      - step:
          name: Test SSH Connection
          script:
            # First, test basic SSH connectivity
            - echo "Testing basic SSH connection..."
            - apt-get update && apt-get install -y openssh-client
            - mkdir -p ~/.ssh
            - echo "Host seojeek.com" >> ~/.ssh/config
            - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            - echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
            - chmod 600 ~/.ssh/config
            
            # Try the SSH pipe with a very simple command
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: 'alxvallejo'
                SERVER: 'seojeek.com'
                COMMAND: 'echo "SSH works!"; pwd; whoami'
                
      - step:
          name: Manual SSH Test
          script:
            # Alternative approach without the pipe
            - echo "Attempting manual SSH test..."
            - apt-get update && apt-get install -y sshpass
            - echo "If this step asks for password, the SSH key is not working"
            # This will fail if password is needed, which tells us the key isn't set up
            - ssh -o BatchMode=yes -o StrictHostKeyChecking=no alxvallejo@seojeek.com "echo 'Connected successfully'" || echo "SSH key authentication failed"